# Generated by Django 5.2.6 on 2025-09-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('student_id', models.CharField()),
                ('is_present', models.BooleanField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
