# Generated by Django 5.2.6 on 2025-09-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='Date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='attend',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='attend',
            name='student_id',
            field=models.CharField(max_length=3),
        ),
    ]
